language: node_js

sudo: false

cache:
  apt: true
  directory:
    - node_modules

node_js: stable

install:
  - npm install -D --legacy-peer-deps
  - cd ./test/smoke/template/
  - npm install -D --legacy-peer-deps
  - cd ../../../

scripts:
  npm test